In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split



In [2]:
perguntas = pd.read_csv('stackoverflow_perguntas.csv')

In [3]:
perguntas.sample(10)

Perguntas          Tags
4435  Tenho o seguinte código desenhado 2 polígonos ...       jquery 
4664  CODE   Aqui eu apenas passo um parâmetro, é po...  html angular
5310  Procurei no SOpt e não encontrei o que desejav...  jquery html 
1704  Estou com problemas para consultar dados de um...  jquery html 
3850  Por exemplo na parte 'Numeral formatting' dest...          html
3944  Preciso desenvolver um menu acordeon e estou t...        jquery
1408  Faço uma requisição assim:   CODE   Tenho um m...        jquery
1123  Eu estive tentando fazer um código para gerar ...       node.js
2495  Quando tento chamar a biblioteca Jquery Mobile...        jquery
5353  Tenho esta variável alterarRegistro : boolean;...       angular

In [4]:
print(len(perguntas))

5408


In [5]:
#Conta quantas tags diferentes existem na coluna Tags
print(len(perguntas.Tags.unique()))

37


In [6]:
#Verifica tags unicas utilizando a funcao unique
lista_de_tags = list()

for tags in perguntas.Tags.unique():
    for tag in tags.split():
        if tag not in lista_de_tags:
            lista_de_tags.append(tag)

print(lista_de_tags)

['node.js', 'jquery', 'html', 'angular']


In [7]:
#Classificando a tag node_js e criando uma coluna para essa tag

node_js = list()

for linha_tag in perguntas.Tags:
    if "node.js" in linha_tag:
        node_js.append(1)
    else:
        node_js.append(0)

perguntas["node_js"] = node_js

perguntas

Perguntas           Tags  \
0     Possuo um projeto Node.js porém preciso criar ...        node.js   
1     Gostaria de fazer testes unitários no Node.js,...        node.js   
2     Como inverter a ordem com que o jQuery itera u...         jquery   
3     Eu tenho uma página onde pretendo utilizar um ...           html   
4     Como exibir os dados retornados do FireStore e...  html angular    
...                                                 ...            ...   
5403  Queria saber como pegar o total de cores de um...   jquery html    
5404  Boa noite, estou usando phonegap para fazer um...          html    
5405  Estou construindo um mini fórum, e nele, os us...    jquery html   
5406  Boa tarde,  Estou para desenvolver um site na ...           html   
5407  Estou fazendo um hotsite, ele é one page, e é ...    jquery html   

      node_js  
0           1  
1           1  
2           0  
3           0  
4           0  
...       ...  
5403        0  
5404        0  
5405        0  
5406        0  
5407        0  

[5408 rows x 3 columns]

In [8]:
#Verifica se a tag
def nova_coluna(lista_tags, dataframe, nome_tags):
    for tag in lista_tags:
        coluna = list()
        for linha_tag in dataframe[nome_tags]:
            if tag in linha_tag:
                coluna.append(1)
            else:
                coluna.append(0)

        dataframe[tag] = coluna 
nova_coluna(lista_de_tags, perguntas, "Tags")
perguntas.sample(10)

Perguntas          Tags  \
3869  Como faço um Jquery para um input de pontos co...        jquery   
2537  Tenho um modal no qual contem uma lista que é ...        jquery   
4377  Estou com um dúvida sobre como um servidor nod...       node.js   
3683  Estou tentando passar o CODE  do CODE  dentro ...       angular   
238                    Como faço isso rodar ?      CODE          html   
1887  Eu estou a tentar criar um formulário muito si...  jquery html    
5288  Fiz a instalação do cordova, instalei  a SDK d...          html   
281   Boa noite,tenho um projeto em html, já está na...         html    
4079  Possuo um script que fica lendo um .log basica...  jquery html    
4299  CODE   Desta maneira ele esta carregando a ima...        jquery   

      node_js  node.js  jquery  html  angular  
3869        0        0       1     0        0  
2537        0        0       1     0        0  
4377        1        1       0     0        0  
3683        0        0       0     0        1  
238         0        0       0     1        0  
1887        0        0       1     1        0  
5288        0        0       0     1        0  
281         0        0       0     1        0  
4079        0        0       1     1        0  
4299        0        0       1     0        0

In [11]:
#Criando uma nova coluna, para juntar todas as tags em uma coluna unica.
lista_zip_tags = list(zip(perguntas[lista_de_tags[0]],
                     perguntas[lista_de_tags[1]],
                     perguntas[lista_de_tags[2]],
                     perguntas[lista_de_tags[3]]))

perguntas["todas_tags"] = lista_zip_tags
perguntas.sample(10)

Perguntas         Tags  node_js  \
4521  tudo bem? Estou com problema para fazer requis...      angular        0   
4917  Utilizo a seguinte biblioteca para gerar os gr...      jquery         0   
4374  Estou precisando saber o tamanho em px do camp...       jquery        0   
1031  Erro ao instalar exp via npm  Expo is a set of...      node.js        1   
3365  Quando clico em uma area e depois no botão .ma...       jquery        0   
4004  Estou fazendo uma landing page que tem um foot...  jquery html        0   
4818  Atualmente o meu schema está definido assim:  ...      node.js        1   
1551  Estou utilizando o LazySizes para carregar ima...       jquery        0   
703   Esto a tentar implementar um servidor capaz de...      node.js        1   
3707  Estou usando ui-router do Angular-Ui e a unica...      angular        0   

      node.js  jquery  html  angular    todas_tags  
4521        0       0     0        1  (0, 0, 0, 1)  
4917        0       1     0        0  (0, 1, 0, 0)  
4374        0       1     0        0  (0, 1, 0, 0)  
1031        1       0     0        0  (1, 0, 0, 0)  
3365        0       1     0        0  (0, 1, 0, 0)  
4004        0       1     1        0  (0, 1, 1, 0)  
4818        1       0     0        0  (1, 0, 0, 0)  
1551        0       1     0        0  (0, 1, 0, 0)  
703         1       0     0        0  (1, 0, 0, 0)  
3707        0       0     0        1  (0, 0, 0, 1)

In [16]:
#Definindo os parametros de testes do modelo e qual aa coluna de referencia
from sklearn.model_selection import train_test_split

perguntas_treino, perguntas_test, tags_treino, tags_teste = train_test_split(
    perguntas.Perguntas, 
    perguntas.todas_tags,
    test_size = 0.2,
    random_state = 123
)

In [18]:
#Criando um vetorizador para classificar as palavras de um texto
from sklearn.feature_extraction.text import TfidfVectorizer

vetorizar = TfidfVectorizer(max_features= 5000, max_df= 0.85)
vetorizar

TfidfVectorizer(max_df=0.85, max_features=5000)

In [22]:
#aplicando um modelo vetorizador para classificar as palavras
vetorizar.fit(perguntas.Perguntas)
perguntas_treino_tfidf = vetorizar.transform(perguntas_treino)
perguntas_test_tfidf = vetorizar.transform(perguntas_test)
print(perguntas_treino_tfidf.shape)
print(perguntas_test_tfidf.shape)

(4326, 5000)
(1082, 5000)


In [30]:
#Convertendo os dados de teste e treino para o formato lista, para processar o modelo de regrassao logistica
import numpy as np

tags_treino_array = np.asarray(list(tags_treino))
tags_teste_array = np.asarray(list(tags_teste))
print(tags_treino_array)

[[0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 ...
 [0 1 1 0]
 [0 0 1 0]
 [0 1 1 0]]


In [32]:
#Rodando o modelo de regressao logista para classificar as perguntas e retornar a acuracia 
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

regressao_logistica = LogisticRegression()
classificador_onevsrest = OneVsRestClassifier(regressao_logistica)
classificador_onevsrest.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_onevsrest = classificador_onevsrest.score(perguntas_test_tfidf, tags_teste_array)
print("Resultado {0: .2f}%".format(resultado_onevsrest*100))


Resultado  41.87%
