In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split



In [2]:
perguntas = pd.read_csv('stackoverflow_perguntas.csv')

In [3]:
perguntas.sample(10)

Perguntas                 Tags
4505  Eu exibo um DropDownList com dois valores SC e...          jquery html
1357  Tenho uma página listando algumas vagas para t...  jquery html angular
1907  Como que eu faço para somente se o input estiv...       jquery angular
2794  Preciso fazer uma página que, quando o usuário...                html 
264   Bom dia.  Na empresa onde trabalho, existe uma...              node.js
5355  Tenho visto que em alguns cadastros, estão usa...         jquery html 
4663  Como mandar o valor do src de uma tag img para...               jquery
762   Supondo uma página que tenha vários eventos se...               jquery
712   Estou com um problema e por mais que pareça si...                 html
924   Estou criando um Menu Accordion, baseando em u...               jquery

In [4]:
print(len(perguntas))

5408


In [5]:
#Conta quantas tags diferentes existem na coluna Tags
print(len(perguntas.Tags.unique()))

37


In [6]:
#Verifica tags unicas utilizando a funcao unique
lista_de_tags = list()

for tags in perguntas.Tags.unique():
    for tag in tags.split():
        if tag not in lista_de_tags:
            lista_de_tags.append(tag)

print(lista_de_tags)

['node.js', 'jquery', 'html', 'angular']


In [7]:
#Classificando a tag node_js e criando uma coluna para essa tag

node_js = list()

for linha_tag in perguntas.Tags:
    if "node.js" in linha_tag:
        node_js.append(1)
    else:
        node_js.append(0)

perguntas["node_js"] = node_js

perguntas

Perguntas           Tags  \
0     Possuo um projeto Node.js porém preciso criar ...        node.js   
1     Gostaria de fazer testes unitários no Node.js,...        node.js   
2     Como inverter a ordem com que o jQuery itera u...         jquery   
3     Eu tenho uma página onde pretendo utilizar um ...           html   
4     Como exibir os dados retornados do FireStore e...  html angular    
...                                                 ...            ...   
5403  Queria saber como pegar o total de cores de um...   jquery html    
5404  Boa noite, estou usando phonegap para fazer um...          html    
5405  Estou construindo um mini fórum, e nele, os us...    jquery html   
5406  Boa tarde,  Estou para desenvolver um site na ...           html   
5407  Estou fazendo um hotsite, ele é one page, e é ...    jquery html   

      node_js  
0           1  
1           1  
2           0  
3           0  
4           0  
...       ...  
5403        0  
5404        0  
5405        0  
5406        0  
5407        0  

[5408 rows x 3 columns]

In [8]:
#Verifica se a tag
def nova_coluna(lista_tags, dataframe, nome_tags):
    for tag in lista_tags:
        coluna = list()
        for linha_tag in dataframe[nome_tags]:
            if tag in linha_tag:
                coluna.append(1)
            else:
                coluna.append(0)

        dataframe[tag] = coluna 
nova_coluna(lista_de_tags, perguntas, "Tags")
perguntas.sample(10)

Perguntas          Tags  \
4912  Como fazer para preencher as estrelas de um "s...        jquery   
984   Estou fazendo um formulario e o usuario tem qu...         html    
5357                                        CODE   CODE        jquery   
5019  Tenho uma imagem dentro de uma div.facebook qu...        jquery   
584   Bom pessoal eu tenho uma div que fica fixa ao ...  jquery html    
3737  Normalmente vou pesquisar no Google primeirame...          html   
4103  Bom dia.  Estou fazendo uma aplicação node.js ...       node.js   
2598  Eu estava lendo que o middleware Express Sessi...       node.js   
3747                                        CODE   CODE       jquery    
4864  Configurei as rotas, porém o componente não re...       angular   

      node_js  node.js  jquery  html  angular  
4912        0        0       1     0        0  
984         0        0       0     1        0  
5357        0        0       1     0        0  
5019        0        0       1     0        0  
584         0        0       1     1        0  
3737        0        0       0     1        0  
4103        1        1       0     0        0  
2598        1        1       0     0        0  
3747        0        0       1     0        0  
4864        0        0       0     0        1

In [9]:
#Criando uma nova coluna, para juntar todas as tags em uma coluna unica.
lista_zip_tags = list(zip(perguntas[lista_de_tags[0]],
                     perguntas[lista_de_tags[1]],
                     perguntas[lista_de_tags[2]],
                     perguntas[lista_de_tags[3]]))

perguntas["todas_tags"] = lista_zip_tags
perguntas.sample(10)

Perguntas          Tags  \
88    Como faço pra pegar a classe (CODE ) do seguin...   jquery html   
4347  Não estou conseguindo as casas decimais corret...        jquery   
5346  Bom galera tenho um projeto em maven, e na min...        jquery   
695   eu quero retornar dados de um arquivo json, po...  jquery html    
4843  Estou com um problema no carrinho de compras n...        jquery   
4841  Tenho um script Ajax de pesquisa sem recarrega...  jquery html    
2010  toda vez que eu arrastar e "dropar" a barra de...        jquery   
2807  O objetivo é um slider-show, porem quero criar...          html   
4596  Como faço para que um script funcione apenas n...          html   
4554  Tenho um autocomplete que funciona perfeitamen...        jquery   

      node_js  node.js  jquery  html  angular    todas_tags  
88          0        0       1     1        0  (0, 1, 1, 0)  
4347        0        0       1     0        0  (0, 1, 0, 0)  
5346        0        0       1     0        0  (0, 1, 0, 0)  
695         0        0       1     1        0  (0, 1, 1, 0)  
4843        0        0       1     0        0  (0, 1, 0, 0)  
4841        0        0       1     1        0  (0, 1, 1, 0)  
2010        0        0       1     0        0  (0, 1, 0, 0)  
2807        0        0       0     1        0  (0, 0, 1, 0)  
4596        0        0       0     1        0  (0, 0, 1, 0)  
4554        0        0       1     0        0  (0, 1, 0, 0)

In [10]:
#Definindo os parametros de testes do modelo e qual aa coluna de referencia
from sklearn.model_selection import train_test_split

perguntas_treino, perguntas_test, tags_treino, tags_teste = train_test_split(
    perguntas.Perguntas, 
    perguntas.todas_tags,
    test_size = 0.2,
    random_state = 123
)

In [11]:
#Criando um vetorizador para classificar as palavras de um texto
from sklearn.feature_extraction.text import TfidfVectorizer

vetorizar = TfidfVectorizer(max_features= 5000, max_df= 0.85)
vetorizar

TfidfVectorizer(max_df=0.85, max_features=5000)

In [12]:
#aplicando um modelo vetorizador para classificar as palavras
vetorizar.fit(perguntas.Perguntas)
perguntas_treino_tfidf = vetorizar.transform(perguntas_treino)
perguntas_test_tfidf = vetorizar.transform(perguntas_test)
print(perguntas_treino_tfidf.shape)
print(perguntas_test_tfidf.shape)

(4326, 5000)
(1082, 5000)


In [13]:
#Convertendo os dados de teste e treino para o formato lista, para processar o modelo de regrassao logistica
import numpy as np

tags_treino_array = np.asarray(list(tags_treino))
tags_teste_array = np.asarray(list(tags_teste))
print(tags_treino_array)

[[0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 ...
 [0 1 1 0]
 [0 0 1 0]
 [0 1 1 0]]


In [14]:
#Rodando o modelo de regressao logista para classificar as perguntas e retornar a acuracia 
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

regressao_logistica = LogisticRegression()
classificador_onevsrest = OneVsRestClassifier(regressao_logistica)
classificador_onevsrest.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_onevsrest = classificador_onevsrest.score(perguntas_test_tfidf, tags_teste_array)
print("Resultado {0: .2f}%".format(resultado_onevsrest*100))


Resultado  41.87%


In [18]:
#Utilizando o modelo de Hamming Loss, para analisar os valores de cada coluna e verificar o resultado, quanto mais proximo de 0, melhor o modelo esta conseguindo classificar.
from sklearn.metrics import hamming_loss

previsao_onevsrest = classificador_onevsrest.predict(perguntas_test_tfidf)
hamming_loss_onevsrest = hamming_loss(tags_teste_array, previsao_onevsrest)
print("Hamming Loss  {0: .2f}".format(hamming_loss_onevsrest))


Hamming Loss   0.19


In [ ]:
#Utilizando um modelo de classificacao em cadeia, para verificar as correlacoes entre as tags.
from skmultilearn.problem_transform import ClassifierChain

classificador_cadeia = ClassifierChain(regressao_logistica)
classificador_cadeia.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_cadeia = classificador_cadeia.score(perguntas_test_tfidf, tags_teste_array)
previsao_cadeia = classificador_cadeia.predict(perguntas_test_tfidf)
hamming_loss_cadeia = hamming_loss(tags_teste_array, previsao_cadeia)
print("Hamming Loss  {0: .2f}".format(hamming_loss_cadeia))
print("Resultado {0: .2f}%".format(resultado_cadeia*100))


Hamming Loss   0.21
Resultado  49.82%


In [21]:
#Utilizando uma biblioteca binaria para melhorar a performance dos modelos anteriores 
from skmultilearn.problem_transform import BinaryRelevance

classificador_br = BinaryRelevance(regressao_logistica)
classificador_br.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_br = classificador_br.score(perguntas_test_tfidf, tags_teste_array)
previsao_br = classificador_br.predict(perguntas_test_tfidf)
hamming_loss_br = hamming_loss(tags_teste_array, previsao_br)
print("Hamming Loss  {0: .2f}".format(hamming_loss_br))
print("Resultado {0: .2f}%".format(resultado_br*100))

Hamming Loss   0.19
Resultado  41.87%


In [ ]:
from skmultilearn.adapt import MLkNN

classificador_mlknn = MLkNN(k=10, s=1.0)
classificador_mlknn.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_mlknn = classificador_mlknn.score(perguntas_test_tfidf, tags_teste_array)
previsao_mlknn = classificador_mlknn.predict(perguntas_test_tfidf)
hamming_loss_mlknn = hamming_loss(tags_teste_array, previsao_mlknn)
print("Hamming Loss  {0: .2f}".format(hamming_loss_mlknn))
print("Resultado {0: .2f}%".format(resultado_mlknn*100))